services:
  real-time-frontend:
    container_name: real-time-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8507:8507"
    networks:
      - ai-advisor-networks

  real-time-platform:
    container_name: real-time-platform
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8007:8007"
    restart: always
    networks:
      - ai-advisor-networks

networks:
  ai-advisor-networks:
    driver: bridge
